words = [
    "CLI",
    "CUDA",
    "DXIL",
    "GLSL",
    "GPGPU",
    "Globber",
    "HLSL",
    "ISPC",
    "LUT",
    "NOLINT",
    "SPIRV",
    "SPRIV",
    "Shaders",
    "cuh",
    "dxbc",
    "dxbcasm",
    "dxilasm",
    "globbing",
    "jslang",
    "jslangbuild",
    "metallib",
    "metallibasm",
    "ptx",
    "shader",
    "slangc",
    "slangvm",
    "spir",
    "spv",
    "spvasm",
    "tesc",
    "wgsl",
    "xrepo",
]
