words = [
    "CLI",
    "CUDA",
    "DXIL",
    "GLSL",
    "GPGPU",
    "Globber",
    "HLSL",
    "NOLINT",
    "SPIRV",
    "SPRIV",
    "Shaders",
    "jslang",
    "jslangbuild",
    "shader",
    "spir",
    "tesc",
    "wgsl",
    "xrepo",
]
