words = [
    "CLI",
    "CUDA",
    "DXIL",
    "GLSL",
    "GPGPU",
    "Globber",
    "HLSL",
    "ISPC",
    "JIT",
    "LUT",
    "NOLINT",
    "SPIRV",
    "SPRIV",
    "SSBO",
    "Shaders",
    "cuh",
    "dxbc",
    "dxbcasm",
    "dxilasm",
    "endlua",
    "globbing",
    "infront",
    "jslang",
    "jslangbuild",
    "meanin",
    "metallib",
    "metallibasm",
    "ptx",
    "shader",
    "slangc",
    "slangvm",
    "somethin",
    "spir",
    "spv",
    "spvasm",
    "tesc",
    "wastin",
    "wgsl",
    "xrepo",
    "xzy",
]
