# this is AI generated boilerplate. Feel free to change it if you really want to, as I certainly don't want to write my own SConstruct.
# if you're confused, do this inside of .../Undecided_Game_Proj : scons --setName=Name_of_your_lib
# use VS Code or VS Studio 2022

import os
import platform
from SCons.Script import Default, Environment, Glob, AddOption, GetOption

env = Environment(
    tools=['default', 'textfile'],
    ENV=os.environ
)

AddOption('--target', dest='lib_name', type='string', default='my_extension', help='Name of the output library (e.g., my_extension)')
AddOption('--godot-cpp-root', dest='godot_cpp_root', type='string', default='godot-cpp', help='Path to the godot-cpp repository.')
AddOption('--build-folder', dest='build_folder', type='string', default='build', help='Name of the output build directory (e.g., build).')
AddOption('--setName', dest='selectedName', type='string', default="gameModuleCPP", help="Sets the name without explicitly searching for the file, unlike --target.")

env['LIB_NAME'] = GetOption('lib_name')
env['GODOT_CPP_ROOT'] = GetOption('godot_cpp_root')
env['BUILD_FOLDER'] = GetOption('build_folder')
env['SET_NAME'] = GetOption('selectedName')

build_dir = env['BUILD_FOLDER']

if (build_dir == 'build'):
    if(env['LIB_NAME'] != 'my_extension'):
        build_dir = env['LIB_NAME']
    
    build_dir = env['SET_NAME']

env['BUILD_FOLDER'] = build_dir

env['GDEXTENSION_BUILD_DIR'] = '#GDProject/Bin/build/' + env['BUILD_FOLDER']

print("Building for architecture x86_64 on platform windows (MSVC)")

env.Append(CXXFLAGS=['/EHsc', '/Zi', '/O2', '/std:c++17', '/DTYPED_METHOD_BIND']) 
env.Append(LINKFLAGS=['/DEBUG'])

env.Append(CPPPATH=[
    '#src',
    env['GODOT_CPP_ROOT'] + '/include',
    env['GODOT_CPP_ROOT'] + '/gen/core/include',
    env['GODOT_CPP_ROOT'] + '/gen/gdextension/include',
    env['GODOT_CPP_ROOT'] + '/gen/include',
    env['GODOT_CPP_ROOT'] + '/gdextension',
])

env.Append(LIBPATH=[
    env['GDEXTENSION_BUILD_DIR'], 
    env['GODOT_CPP_ROOT'] + '/bin'
])

env.Append(LIBS=['libgodot-cpp.windows.template_debug.x86_64'])


env.SConscript('SConscript', exports='env')

env.Alias('all', env['GDEXTENSION_BUILD_DIR'])
Default(env['GDEXTENSION_BUILD_DIR'])
