import os
import platform
from SCons.Script import Default, Environment, Glob, AddOption, GetOption
from SCons.Errors import UserError

env = Environment(ENV=os.environ)

#env = Environment(
#tools=['msvc', 'mslink', 'textfile'], ENV=os.environ
#)

AddOption('--target', dest='lib_name', type='string', default='my_extension', help='Name of the output library (e.g., my_extension)')
AddOption('--targetFolder', dest='target_folder', type='string', default='err', help='Name of the target folder. "src" is considered the root - everything else must be local to it.')
AddOption('--godot-cpp-root', dest='godot_cpp_root', type='string', default='godot-cpp', help='Path to the godot-cpp repository.')
AddOption('--build-folder', dest='build_folder', type='string', default='build', help='Name of the output build directory (e.g., build).')
AddOption('--setName', dest='selectedName', type='string', default="gameModuleCPP", help="Sets the name without explicitly searching for the file, unlike --target.")
AddOption('--productionBuild', dest='prod_build', type='int', default='false', help='Determines if debug mode should be activated or not.')
AddOption('--compileFor', dest='compile_for', type='string', default='Windows', help='Which platform to compile for. e.g., Windows, Linux.')

env['LIB_NAME'] = GetOption('lib_name')
env['GODOT_CPP_ROOT'] = GetOption('godot_cpp_root')
env['BUILD_FOLDER'] = GetOption('build_folder')
env['SET_NAME'] = GetOption('selectedName')
env['SWITCH_CASE'] = 0
env['TARGET_FOLDER'] = GetOption("target_folder")
env['PRODUCTION_BUILD'] = GetOption("prod_build")
env['PLATFORM'] = GetOption("compile_for")

build_dir = ''

if(env['LIB_NAME'] != 'my_extension' and env['SET_NAME'] == 'gameModuleCPP'):
    build_dir = env['LIB_NAME']
    env['SWITCH_CASE'] = 0
elif(env['LIB_NAME'] != 'my_extension' and env['SET_NAME'] != 'gameModuleCPP'):
    build_dir = env['SET_NAME']
    env['SWITCH_CASE'] = 1
else:
    raise UserError("--target is undefined.")

if env['TARGET_FOLDER'] == 'err':
    raise UserError("--targetFolder is undefined.")

env['BUILD_FOLDER'] = build_dir

env['GDEXTENSION_BUILD_DIR'] = '#GDProject/Bin/build/' + env['BUILD_FOLDER']

if env['PRODUCTION_BUILD'] == 1:
    env.Append(CPPDEFINES=['PRODUCTION_BUILD'])
    print("Appending production build definition.")

if env['PLATFORM'] == 'Linux':
    env.Append(CXXFLAGS=['-g', '-O2', '-std=gnu++17', '-DTYPED_METHOD_BIND'])
elif env['PLATFORM'] == 'Windows':
    env.Append(CXXFLAGS=['/EHsc', '/Zi', '/O2', '/std:c++17', '/DTYPED_METHOD_BIND']) 

if env['PLATFORM'] == 'Windows':
    env.Append(LINKFLAGS=['/DEBUG'])

env.Append(CPPPATH=[
'#src',
    env['GODOT_CPP_ROOT'] + '/include',
    env['GODOT_CPP_ROOT'] + '/gen/core/include',
    env['GODOT_CPP_ROOT'] + '/gen/gdextension/include',
    env['GODOT_CPP_ROOT'] + '/gen/include',
    env['GODOT_CPP_ROOT'] + '/gdextension',
])

env.Append(LIBPATH=[
    env['GDEXTENSION_BUILD_DIR'], 
    env['GODOT_CPP_ROOT'] + '/bin'
])

if env['PLATFORM'] == 'Windows':
    env.Append(LIBS=['libgodot-cpp.windows.template_debug.x86_64'])
elif env['PLATFORM'] == 'Linux':
    env.Append(LIBS=['libgodot-cpp.linux.template_debug.x86_64'])

env.SConscript('SConscript', exports='env')

env.Alias('all', env['GDEXTENSION_BUILD_DIR'])
Default(env['GDEXTENSION_BUILD_DIR'])