#!/usr/bin/env python

import os
import sys
from SCons.Script import ARGUMENTS, Dir, Tool

# Add godot-cpp folder to sys.path, so that we can import local modules.
godot_cpp_root = Dir(".").srcnode().abspath
sys.path.append(godot_cpp_root)
sys.path.append(os.path.join(godot_cpp_root, "tools"))

EnsureSConsVersion(4, 0)
EnsurePythonVersion(3, 8)

try:
    Import("env")
except Exception:
    # Default tools with no platform defaults to gnu toolchain.
    # We apply platform specific toolchains via our custom tools.
    env = Environment(tools=["default"], PLATFORM="")

if ARGUMENTS.get("platform") == "macos":
    import tools.macos as godot_macos
    godot_macos.exists = lambda environment: True

env.PrependENVPath("PATH", os.getenv("PATH"))
for var in ["APPDATA", "LOCALAPPDATA", "USERPROFILE", "HOMEDRIVE", "HOMEPATH"]:
    val = os.getenv(var)
    if val:
        env["ENV"][var] = val

# Custom options and profile flags.
customs = ["custom.py"]
try:
    customs += Import("customs")
except Exception:
    pass
profile = ARGUMENTS.get("profile", "")
if profile:
    if os.path.isfile(profile):
        customs.append(profile)
    elif os.path.isfile(profile + ".py"):
        customs.append(profile + ".py")
opts = Variables(customs, ARGUMENTS)
cpp_tool = Tool("godotcpp", toolpath=[Dir("tools").srcnode().abspath])
cpp_tool.options(opts, env)
opts.Update(env)
Help(opts.GenerateHelpText(env))

is_windows = env["platform"] == "windows"

if(not is_windows): 
    print("Platform not windows; switching to LLVM...")
    env["use_llvm"] = True

# Detect and print a warning listing unknown SCons variables to ease troubleshooting.
unknown = opts.UnknownVariables()
if unknown:
    print("WARNING: Unknown SCons variables were passed and will be ignored:")
    for item in unknown.items():
        print("    " + item[0] + "=" + item[1])

scons_cache_path = os.environ.get("SCONS_CACHE")
if scons_cache_path is not None:
    CacheDir(scons_cache_path)
    Decider("MD5")

cpp_tool.generate(env)

target_os = ARGUMENTS.get("target_os", env["platform"])
target_os = "linux" if len(target_os) <= 0 else target_os

if(not is_windows):
    if "suffix" in env:
        env["suffix"] = env["suffix"].replace(f".{env['platform']}.", f".{target_os}.")

    old_platform_string = f".{env['platform']}.{env['target']}"
    new_platform_string = f".{target_os}.{env['target']}"
    
    if "OBJSUFFIX" in env:
        env["OBJSUFFIX"] = env["OBJSUFFIX"].replace(old_platform_string, new_platform_string)

    env["CC"] = "zig cc"
    env["CXX"] = "zig c++"
    env["LINK"] = "zig c++"
    #env["AR"] = "zig ar"

    zig_target = ""
    if target_os == "linux": 
        zig_target = ["-target", "x86_64-linux"]
    elif target_os == "macos": 
        zig_target = ["-target", "x86_64-macos"]

        if "CPPDEFINES" in env:
            env["CPPDEFINES"] = [d for d in env["CPPDEFINES"] if d != "LINUX_ENABLED"]

        env.Append(CPPDEFINES=["MACOS_ENABLED", "UNIX_ENABLED"])

        TLS_model = "-fno-emulated-tls -pthread"
        env.Append(CCFLAGS=TLS_model)
        env.Append(LINKFLAGS=TLS_model)
        
    env.Append(CFLAGS=zig_target)
    env.Append(CCFLAGS=zig_target)
    env.Append(LINKFLAGS=zig_target)

    def AR_Command(target, source, env):
        import subprocess
        import sys
        
        target_string = os.path.normpath(str(target[0]))

        if os.path.exists(target_string):
            try:
                os.remove(target_string)
            except OSError:
                return 1
            
        #for s in source:
        #    print("Source contains: ", str(s))
        #    print("Norm path: ", os.path.normpath(str(s)))

        source_strings = [os.path.normpath(str(s)) for s in source]
        zig_chunk_size = 50
        for i in range(0, len(source_strings), zig_chunk_size):
            zig_chunk = source_strings[i: i + zig_chunk_size]

            cmd = ["zig", "ar", "q", target_string] + zig_chunk
            try:
                subprocess.run(cmd, check=True, capture_output=True, text=True)
            except subprocess.CalledProcessError as e:
                print(f"Zig ar failed: {e.stderr}")
                return 1
                
        return 0

    env["ARCOM"] = Action(AR_Command, "Archiving $TARGET with Zig chunks...")

    env["RANLIB"] = "zig ranlib"

    #env["ARCOM"] = "${TEMPFILE('$AR $ARFLAGS $TARGET $SOURCES', '$ARCOMSTR')}"
    env["LINK"] = ["zig", "c++"]
    env["LINKCOM"] = "${TEMPFILE('$LINK $LINKFLAGS $_LINKFLAGS -o $TARGET $SOURCES $_LIBDIRFLAGS $_LIBFLAGS', '$LINKCOMSTR')}"

    if "CCFLAGS" in env:
        env["CCFLAGS"] = [f for f in env["CCFLAGS"] if not f.startswith("-march=")]
    if "CFLAGS" in env:
        env["CFLAGS"] = [f for f in env["CFLAGS"] if not f.startswith("-march=")]

library = env.GodotCPP()

Return("env")
